kind: Service
apiVersion: v1
metadata:
  name: hospital-api-service   
  namespace: nm
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80      
  selector:
    app:  hospital-api