apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: hospital-processor-scaler
  namespace: nm
  labels:
    app: hospital-api-scaledobject
    name: hospital-api-scaledobject
spec:
  scaleTargetRef:
    name: hospital-api
  minReplicaCount: 1 #Change to define how many minimum replicas you want
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus
    metadata:
      namespace: demobusk8
      queueName: queuecityworksnet 
      queueLength: '1'
    authenticationRef:
      name: trigger-auth-service-bus-hospital